// <auto-generated />
using System;
using GymManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601143103_AlterMemberAttendancRelation")]
    partial class AlterMemberAttendancRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("BaseUserSequence");

            modelBuilder.Entity("GymManagement.Domain.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [BaseUserSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("GymManagement.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GymManagement.Domain.EmployeeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("ClockIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ClockOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("LateBy")
                        .HasColumnType("time");

                    b.Property<decimal?>("LatePenalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OvertimeBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan?>("OvertimeHours")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeAttendance");
                });

            modelBuilder.Entity("GymManagement.Domain.MemberAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MemberPlansId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberPlansId");

                    b.ToTable("MemberAttendances");
                });

            modelBuilder.Entity("GymManagement.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Manager"
                        });
                });

            modelBuilder.Entity("GymManagement.Domain.Scheduling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("WeekDaysId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekDaysId");

                    b.ToTable("Schedulings");
                });

            modelBuilder.Entity("GymManagement.Domain.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDaysPerPlans")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlansFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes");
                });

            modelBuilder.Entity("GymManagement.Domain.WeekDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeekDays");
                });

            modelBuilder.Entity("GymManagement.Domain.Employee", b =>
                {
                    b.HasBaseType("GymManagement.Domain.BaseUser");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("ResignationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            PhoneNumber = "010555454545",
                            RoleId = 1,
                            UserName = "RenadAbdelhakem",
                            HireDate = new DateOnly(2026, 6, 1),
                            IsActive = true,
                            Salary = 0m
                        });
                });

            modelBuilder.Entity("GymManagement.Domain.Member", b =>
                {
                    b.HasBaseType("GymManagement.Domain.BaseUser");

                    b.Property<int?>("AvailableDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrivateMember")
                        .HasColumnType("bit");

                    b.Property<int?>("MemberPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipPlansId")
                        .HasColumnType("int");

                    b.Property<int?>("PrivateTrainerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("subscriptionEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("subscriptionStartDate")
                        .HasColumnType("date");

                    b.HasIndex("MembershipPlansId");

                    b.HasIndex("PrivateTrainerId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GymManagement.Domain.BaseUser", b =>
                {
                    b.HasOne("GymManagement.Domain.Role", "Role")
                        .WithMany("BaseUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GymManagement.Domain.Course", b =>
                {
                    b.HasOne("GymManagement.Domain.Employee", "Employee")
                        .WithMany("Course")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GymManagement.Domain.EmployeeAttendance", b =>
                {
                    b.HasOne("GymManagement.Domain.Employee", "Employee")
                        .WithMany("EmployeeAttendancecs")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("GymManagement.Domain.MemberAttendance", b =>
                {
                    b.HasOne("GymManagement.Domain.Member", "Member")
                        .WithMany("MemberAttendancecs")
                        .HasForeignKey("MemberId");

                    b.HasOne("GymManagement.Domain.SubscriptionType", "MembershipPlans")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MemberPlansId");

                    b.Navigation("Member");

                    b.Navigation("MembershipPlans");
                });

            modelBuilder.Entity("GymManagement.Domain.Scheduling", b =>
                {
                    b.HasOne("GymManagement.Domain.Course", "Course")
                        .WithMany("Schedulings")
                        .HasForeignKey("CourseId");

                    b.HasOne("GymManagement.Domain.Employee", "Employee")
                        .WithMany("Schedulings")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("GymManagement.Domain.WeekDays", "WeekDays")
                        .WithMany("Schedulings")
                        .HasForeignKey("WeekDaysId");

                    b.Navigation("Course");

                    b.Navigation("Employee");

                    b.Navigation("WeekDays");
                });

            modelBuilder.Entity("GymManagement.Domain.Member", b =>
                {
                    b.HasOne("GymManagement.Domain.SubscriptionType", "MembershipPlans")
                        .WithMany("Members")
                        .HasForeignKey("MembershipPlansId");

                    b.HasOne("GymManagement.Domain.Employee", "Employee")
                        .WithMany("PrivateMembers")
                        .HasForeignKey("PrivateTrainerId");

                    b.Navigation("Employee");

                    b.Navigation("MembershipPlans");
                });

            modelBuilder.Entity("GymManagement.Domain.Course", b =>
                {
                    b.Navigation("Schedulings");
                });

            modelBuilder.Entity("GymManagement.Domain.Role", b =>
                {
                    b.Navigation("BaseUsers");
                });

            modelBuilder.Entity("GymManagement.Domain.SubscriptionType", b =>
                {
                    b.Navigation("MemberAttendances");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GymManagement.Domain.WeekDays", b =>
                {
                    b.Navigation("Schedulings");
                });

            modelBuilder.Entity("GymManagement.Domain.Employee", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("EmployeeAttendancecs");

                    b.Navigation("PrivateMembers");

                    b.Navigation("Schedulings");
                });

            modelBuilder.Entity("GymManagement.Domain.Member", b =>
                {
                    b.Navigation("MemberAttendancecs");
                });
#pragma warning restore 612, 618
        }
    }
}
